import turtle as tt
from time import sleep, localtime as l_time, time as time_

tt.ht()
tt.speed("fastest")
tt.tracer(0, 0)
tt.pu()
tt.pensize(3)
tt.fd(200)
tt.left(90)
tt.pd()
tt.circle(200)
tt.left(90)
s = ["Ⅲ", "Ⅱ", "Ⅰ", "Ⅻ", "Ⅺ", "Ⅹ", "Ⅸ", "Ⅷ", "Ⅶ", "Ⅵ", "Ⅴ", "Ⅳ"]
font = ("华文宋体", 20, "bold")
for i in range(12):
    tt.pd()
    tt.pensize(2)
    tt.fd(10)
    tt.back(10)
    tt.right(90)
    for j in range(5):
        tt.pensize(1)
        tt.circle(200, 6)
        tt.left(90)
        tt.fd(5)
        tt.back(5)
        tt.right(90)
    tt.left(90)
tt.pu()
tt.back(20)
tt.left(90)
tt.fd(15)
tt.right(180)
for i in range(12):
    tt.write(s[i], font=font, align="center")
    tt.circle(220, 30)
tt.home()
tt.dot(10)
tt.pendown()
tt.tracer(True)
while True:
    tt.home()
    time = l_time(time_())
    time = [time[3], time[4] + time[5] // 60, time[5]]
    time = [- time[0] % 12 * 30 - time[1] // 2, - time[1] * 6, - time[2] * 6]
    tt.setheading(time[2] + 90)
    tt.fd(120)
    tt.home()
    tt.setheading(time[1] + 90)
    tt.fd(80)
    tt.home()
    tt.setheading(time[0] + 90)
    tt.fd(50)
    sleep(0.5)
    tt.undo()
    tt.undo()
    tt.undo()
    tt.undo()
    tt.undo()
    tt.undo()
    tt.undo()
    tt.undo()
    tt.undo()
